---
- name: AWX Linux Server Test
  hosts: all
  become: true

  tasks:
    - name: Check hostname
      ansible.builtin.command: hostname
      register: hostname_output
      changed_when: false

    - name: Display hostname
      ansible.builtin.debug:
        var: hostname_output.stdout

    - name: Check uptime
      ansible.builtin.command: uptime
      register: uptime_output
      changed_when: false

    - name: Display uptime
      ansible.builtin.debug:
        var: uptime_output.stdout